= NgRx Workshop

These are notes and code snippets from the NgRx-part of the Udemy Workshop https://www.udemy.com/the-complete-guide-to-angular-2[The complete guide to Angular], which is very much recommended. My notes to the rest of the topics from the guide can be found https://github.com/msg-DAVID-GmbH/AngularWorkshop[here].

== NgRx

* reactive extensions for Angular
* alternative to storing state in an Angular application
* traditional way of using _Subject_ in services = good thing because making sure that statechange only in this service + notification to rest of application
* however: maintaining state in complex applications can become burdensome
* different approach in NgRx: store state globally in key-value-pairs in one place + components can subscribe for changes

== Redux-like pattern
* like in React: only one central *Store* in application
* changing state through *Actions* that gets send to *Reducers*
* state-change immutable: old state doesn't get overwritten but archived

== Creating a Reducer
* reducers add a new state
* parameters will be passed in function automatically by NgRx
* reducer-function will be triggered whenever an action is dispatched
* arguments of reducer-function:
1. State before the function is entered. If no state present, initial state can be determined. The spread-operator "..." means "take the old state"
1. action that overrides the specified part of the old state
* so basically the following says "take the old state and override _beverage_ with the payload from the action"

*bar-reducers.ts*:

[source, javascript]
----
import * as BarActions from './my.actions';
import {Beverage} from './beverage';

const initialState = {
  beverage: new Beverage('Club Mate', 1)
};

export function beverageReducer(state = initialState, action: BarActions.AddBeverage) {

  switch (action.type) {
    case BarActions.ADD_BEVERAGE:
      return {
        ...state,
        beverage: action.payload
      };
    default:
      return state;
  }
}
----

*bar-actions.ts*:

[source,javascript]
----
import {Action} from '@ngrx/store';
import {Beverage} from './beverage';

export const ADD_BEVERAGE = 'ADD_BEVERAGE';

export class AddBeverage implements Action {

  constructor(public payload: Beverage) {
  }

  readonly type = ADD_BEVERAGE;
}

export type BarActions = AddBeverage;
----

* The constant _ADD_BEVERAGE_ is internally used by NgRx to identify actions. Actions with the same identifier will be triggered all after another!

*app.module.ts*:

[source,javascript]
----
imports: [
  ...
  StoreModule.forRoot({beverageReducers: beverageReducer})
]
----

(Attention: There's a best practice to centrally manage all reducers in an own file, see below)

== Getting state & Dispatch Actions

* in constructor: global state has to be defined as JSON-object
* getting state: _this.store.select_
* dispatching actions: _this.store.dispatch_

[source,javascript]
----
export class AppComponent {

  valueFromStore: Beverage;

  constructor(private store: Store<Beverage>) {
  }

  onInputNewValue(form: NgForm) {

    const beverage = new Beverage(form.value.name, form.value.price);

    console.log('Writing to store:');
    console.log(beverage);

    this.store.dispatch(new BarActions.AddBeverage(beverage));

    console.log('Reading from store ...');

    this.store.select('beverageReducers').subscribe(stateObject => {
      this.valueFromStore = stateObject.beverage;
    });

  }
----

== Enhance Readability by using Interfaces for the State

_my.reducers.ts_:

[source,javascript]
----
export interface AppState {
  beverageModule: State;
}

export interface State {
  beverages: Beverage[];
  totalPrice: number;
}

const initialState: State = {
  beverages: [new Beverage('Club Mate', 0)],
  totalPrice: 0
};
----

used in _app.component.ts_:
[source,javascript]
----
constructor(private store: Store<fromBeverageModule.AppState>) {}
----

(instead of having to copy the specific state like this previous version (pretty simple state, but imagine it gets more complicated)):

[source,javascript]
----
constructor(private store: Store<Beverage>) {}
----

== Dealing with Observables by using async-Pipe
* the whole state of a store is always returned as an observable, hence simple string values cannot be used in template like this:

[source,html]
----
This is my value: {{value}}
----

* instead, https://codecraft.tv/courses/angular/pipes/async-pipe/[_async_-pipe] has to be used to get rid of the observable:

[source,html]
----
This is my value: {{value | async}}
----

Here's how fields of a state can be accessed:

* state definition in reducer-file:
[source,javascript]
----
export interface State {
  beverages: Beverage[];
  totalPrice: number;
}
----
** usage: State itself is an observable, fields can be accessed via _subscribe()_:
[source,javascript]
----
    this.store.select('bar').subscribe(stateObject => {
      this.valueFromStore = stateObject.beverages;
      this.totalPrice = stateObject.totalPrice;
    });
----

== Always work on copy of state
* when working with NgRx, past states must not be changed
* instead, create copy of it and work on thi s copy
* example: in reducer when removing a beverage, *don't* change a past state this way:

[source,javascript]
----
const beverages = state.beverages; // DON`T DO THAT!
beverages.splice(action.payload, 1);
----

* instead, create a copy of the past state to work on:

[source,javascript]
----
const beverages = [...state.beverages]; // get old beverages in an immutable way
beverages.splice(action.payload, 1);
----

* uses the https://basarat.gitbooks.io/typescript/docs/spread-operator.html[spread-operator] which spreads the content of an array
* additionally, the spread contents are framed by an array which makes it the same datatype as past state 

* also works for objects:

[source,javascript]
----
const oldStuff = {...state.stuff[index]};
----

== Asynchronous Operations
* for example: storing authentication token in store generally good idea; but getting this token from server will be asynchronous
* problem: asynchronous operations cannot be handled by reducers!

== Centrally manage State and Reducers
* good practice: manage _AppState_-interface and reducers in a file like _/store/app.reducers.ts_:

[source,javascript]
----
import * as fromBarAndPubSupplier from '../bar-and-pub-supplier/store/bar-and-pub-supplier-reducers';
import * as fromBar from '../bar/store/bar-reducers';
import {ActionReducerMap} from '@ngrx/store';

export interface AppState {
  bar: fromBar.State;
  barAndPubSupplier: fromBarAndPubSupplier.State;
}

export const reducers: ActionReducerMap<AppState> = {
  bar: fromBar.barReducer,
  barAndPubSupplier: fromBarAndPubSupplier.barAndPubSupplierReducer
};
----

* referenced in _app.module.ts_:
[source,javascript]
----

@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...
    StoreModule.forRoot(reducers)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
----

== take(1)
* _store.select()_ returns an _Observable_ that can be subscribed to via _subscribe()_:

[source,javascript]
----
this.store.select('barAndPubSupplier').subscribe(stateObject => {
  this.valueFromStore = stateObject.beverages;
  this.totalPrice = stateObject.totalPrice;
});
----

* whenever store changes, subscription is fired
* to have it fire only once to avoid unwanted side-effects:

[source,javascript]
----
this.store.pipe(select('barAndPubSupplier'), take(1)).subscribe(stateObject => {
  .take(1)
  .subscribe(stateObject => {
    this.valueFromStore = stateObject.beverages;
    this.totalPrice = stateObject.totalPrice;
});
----


== Redux Devtools
* https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd[Browser extension for Chrome]
* Necessary changes in source:
* _package.json_:
[source,javascript]
----
  "dependencies": {
    "@ngrx/store-devtools": "^7.2.0",
    ...
----
* _app.modules.ts_:
[source,javascript]
----
  imports: [
    ...
    StoreDevtoolsModule.instrument({
      maxAge: 200, // Retains last 25 states
      logOnly: environment.production, // Restrict extension to log-only mode
    }),
    StoreDevtoolsModule.instrument({ maxAge: 25, logOnly: environment.production }),
  ],
  ...
----

== Further Reading
=== Always use NgRX?
* https://blog.angular-university.io/angular-2-redux-ngrx-rxjs/[Angular Service Layers: Redux, RxJs and Ngrx Store - When to Use a Store and why]:
** stores not viewed by their creators as a one-size-fits-all-solution: "_You’ll know when you need Flux. If you aren’t sure if you need it, you don’t need it._"
* https://redux.js.org/faq/general#when-should-i-learn-redux[When should I use Redux?]:
** "_I would like to amend this: don't use Redux until you have problems with vanilla React._"
** "_However, it's also important to understand that using Redux comes with tradeoffs. It's not designed to be the shortest or fastest way to write code. It's intended to help answer the question "When did a certain slice of state change, and where did the data come from?", with predictable behavior._"

=== What data to put into the store?
* https://medium.com/@stodge/which-types-of-state-should-be-placed-in-my-ngrx-store-e6d2749333f1[Which types of state should be placed in my NGRX store?]: 
** global reference data that has to be cached in the browser, for example shopping cart or wizard progress
** complex component interactions that would be hard to implement using bindings and event emitters
** "_Any properties of services in Angular (or AngularJs) are strong candidates to be placed into the store._"

=== Is global State with NgRx an antipattern?
* https://kimsereyblog.blogspot.com/2017/07/managing-global-state-with-ngrx-store.html[Managing global state with NgRx store in Angular]
* "_Global state has had a bad reputation since inception due to its unpredictable nature.
    About two years ago, Redux was introduced as a way to manage this unpredictability by making the state immutable and operations acting on the state synchronous and stateless (a similiar approach can be found in the actor pattern).
    Since then, its principales has inspired multiple implementations, one of them being the Ngrx store for Angular._"
* https://discuss.reactjs.org/t/redux-and-global-state-vs-local-state/4187[Redux and global state vs. local state]
